force-app/main/default/objects/South_African_ID__c/South_African_ID__c.object-meta.xml
<CustomObject>
    <label>South African ID</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>South African IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/South_African_ID__c/fields/Citizenship__c.field-meta.xml
<CustomField>
    <fullName>Citizenship__c</fullName>
    <label>Citizenship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
            <value>
                <fullName>SA Citizen</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/South_African_ID__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Male</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/South_African_ID__c/fields/ID_Number__c.field-meta.xml
<CustomField>
    <fullName>ID_Number__c</fullName>
    <externalId>true</externalId>
    <label>ID Number</label>
    <length>13</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SouthAfricanIDQueries.cls
public class SouthAfricanIDQueries
{
    public static List<South_African_ID__c> getByIdNumber(List<String> idNumbers)
    {
        return 
        [
            SELECT
                Id,
                Citizenship__c,
                Date_of_Birth__c,
                Gender__c,
                ID_Number__c,
                Search_Count__c
            FROM
                South_African_ID__c
            WHERE
                ID_Number__c IN: idNumbers

        ];
    }
}